apiVersion: v2
appVersion: "v4.3.5-docker-11"
description: A Helm chart for Kubernetes
name: grr
type: application
version: 0.1.0
dependencies:
  - name: mariadb
    version: 19.0.5
    repository: https://charts.bitnami.com/bitnami
